services:
  lunark-web:
    image: lunark-web:latest
    container_name: lunark-web
    restart: always
    env_file:
      - .env.production
    ports:
      - "3004:3000"
    networks:
      - lunark-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  lunark-network:
    driver: bridge
